- job:
    name: cloudkittyclient-devstack-functional
    parent: devstack
    description: |
      Job for cloudkittyclient functional tests
    pre-run: playbooks/cloudkittyclient-devstack-functional/pre.yaml
    run: playbooks/cloudkittyclient-devstack-functional/run.yaml
    post-run: playbooks/cloudkittyclient-devstack-functional/post.yaml
    required-projects:
      - name: openstack/cloudkitty
      - name: openstack/python-cloudkittyclient
    roles:
      - zuul: openstack-infra/devstack
    timeout: 5400
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
    vars:
      devstack_plugins:
        cloudkitty: https://opendev.org/openstack/cloudkitty
      devstack_localrc:
        CLOUDKITTY_FETCHER: keystone
      devstack_services:
        ck-api: true
        horizon: false
      tox_install_siblings: false
      zuul_work_dir: src/opendev.org/openstack/python-cloudkittyclient
      tox_envlist: functional

- job:
    name: cloudkittyclient-devstack-functional-py3
    parent: cloudkittyclient-devstack-functional
    description: |
      Job for cloudkittyclient functional tests, ran in python3.
    vars:
      devstack_localrc:
        DEVSTACK_GATE_USE_PYTHON3: "True"
        USE_PYTHON3: "True"

- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python-jobs
      - openstack-python3-train-jobs
      - openstackclient-plugin-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - cloudkittyclient-devstack-functional:
            voting: true
        - cloudkittyclient-devstack-functional-py3:
            voting: true
    gate:
      jobs:
        - cloudkittyclient-devstack-functional:
            voting: true
        - cloudkittyclient-devstack-functional-py3:
            voting: true
